#!/bin/bash

BASE_URL="https://geo2day.com/asia/india/"

FILES=(
"andaman_and_nicobar_islands.pbf"
"andhra_pradesh.pbf"
"arunachal_pradesh.pbf"
"assam.pbf"
"bihar.pbf"
"central-zone.pbf"
"chandigarh.pbf"
"chhattisgarh.pbf"
"dadra_and_nagar_haveli.pbf"
"dadra_and_nagar_haveli_and_daman_and_diu.pbf"
"daman_and_diu.pbf"
"eastern-zone.pbf"
"goa.pbf"
"gujarat.pbf"
"haryana.pbf"
"himachal_pradesh.pbf"
"jammu_and_kashmir.pbf"
"jharkhand.pbf"
"karnataka.pbf"
"kerala.pbf"
"lakshadweep.pbf"
"madhya_pradesh.pbf"
"maharashtra.pbf"
"manipur.pbf"
"meghalaya.pbf"
"mizoram.pbf"
"nagaland.pbf"
"national_capital_territory_of_delhi.pbf"
"north-eastern-zone.pbf"
"northern-zone.pbf"
"odisha.pbf"
"puducherry.pbf"
"punjab.pbf"
"rajasthan.pbf"
"sikkim.pbf"
"southern-zone.pbf"
"tamil_nadu.pbf"
"telangana.pbf"
"tripura.pbf"
"uttar_pradesh.pbf"
"uttarakhand.pbf"
"west_bengal.pbf"
"western-zone.pbf"
)

for f in "${FILES[@]}"
do
    echo "Downloading $f"
    wget "${BASE_URL}${f}"
done

echo "All downloads complete."
