- hosts: localhost
  become: true
  vars:
    pbf_dir: /root/geo2day_india
    shortbread_dir: /root/geo2day_mbtiles_india_shortbread
    openmaptiles_dir: /root/geo2day_mbtiles_india_openmaptiles
    routing_dir: /root/geo2day_routing_india
    # Temporary config directories
    shortbread_config_dir: /tmp/shortbread_configs
    openmaptiles_config_dir: /tmp/openmaptiles_configs

  tasks:
    - name: ensure output directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ shortbread_dir }}"
        - "{{ openmaptiles_dir }}"
        - "{{ routing_dir }}"
        - "{{ shortbread_config_dir }}"
        - "{{ openmaptiles_config_dir }}"

    # ---------- Download Shortbread configs ----------------------------------------
    - name: download shortbread config.json
      get_url:
        url: https://raw.githubusercontent.com/shortbread-tiles/shortbread-tilemaker/master/config.json
        dest: "{{ shortbread_config_dir }}/config-shortbread.json"
        mode: '0644'

    - name: download shortbread process.lua
      get_url:
        url: https://raw.githubusercontent.com/shortbread-tiles/shortbread-tilemaker/master/process.lua
        dest: "{{ shortbread_config_dir }}/process-shortbread.lua"
        mode: '0644'

    # ---------- Download OpenMapTiles configs ---------------------------------------
    - name: download openmaptiles config.json
      get_url:
        url: https://raw.githubusercontent.com/systemed/tilemaker/master/resources/config-openmaptiles.json
        dest: "{{ openmaptiles_config_dir }}/config-openmaptiles.json"
        mode: '0644'

    - name: download openmaptiles process.lua
      get_url:
        url: https://raw.githubusercontent.com/systemed/tilemaker/master/resources/process-openmaptiles.lua
        dest: "{{ openmaptiles_config_dir }}/process-openmaptiles.lua"
        mode: '0644'

    # ---------- 1. Shortbread tiles -------------------------------------------------
    - name: pull tilemaker image (latest stable)
      community.docker.docker_image:
        name: ghcr.io/systemed/tilemaker:master
        source: pull

    - name: shortbread – pbf → mbtiles
      community.docker.docker_container:
        name: shortbread-job
        image: ghcr.io/systemed/tilemaker:master
        platform: linux/arm64
        command: >
          bash -c 'set -e;
          for f in /pbf/*.pbf; do
            base=$(basename "$f" .pbf);
            tilemaker --input "$f"
                      --output /out/${base}.mbtiles
                      --config /configs/config-shortbread.json
                      --process /configs/process-shortbread.lua;
          done'
        volumes:
          - "{{ pbf_dir }}:/pbf:ro"
          - "{{ shortbread_dir }}:/out"
          - "{{ shortbread_config_dir }}:/configs:ro"
        cleanup: true
        detach: false

    # ---------- 2. OpenMapTiles style -----------------------------------------------
    - name: openmaptiles – pbf → mbtiles
      community.docker.docker_container:
        name: omt-job
        image: ghcr.io/systemed/tilemaker:master
        platform: linux/arm64
        command: >
          bash -c 'set -e;
          for f in /pbf/*.pbf; do
            base=$(basename "$f" .pbf);
            tilemaker --input "$f"
                      --output /out/${base}.mbtiles
                      --config /configs/config-openmaptiles.json
                      --process /configs/process-openmaptiles.lua;
          done'
        volumes:
          - "{{ pbf_dir }}:/pbf:ro"
          - "{{ openmaptiles_dir }}:/out"
          - "{{ openmaptiles_config_dir }}:/configs:ro"
        cleanup: true
        detach: false

    # ---------- 3. Valhalla routing graph -------------------------------------------
    - name: pull valhalla image
      community.docker.docker_image:
        name: ghcr.io/valhalla/valhalla:latest
        source: pull

    - name: valhalla – pbf → routing tiles
      community.docker.docker_container:
        name: valhalla-job
        image: ghcr.io/valhalla/valhalla:latest
        platform: linux/arm64
        command: >
          bash -c 'set -e;
          for f in /pbf/*.pbf; do
            base=$(basename "$f" .pbf);
            mkdir -p /out/${base}_tiles;
            valhalla_build_config \
              --mjolnir-tile-dir /out/${base}_tiles \
              --mjolnir-tile-extract /out/${base}.tar \
              --mjolnir-timezone /out/${base}_tiles/timezones.sqlite \
              --mjolnir-admin /out/${base}_tiles/admins.sqlite > /tmp/${base}.json;
            valhalla_build_tiles -c /tmp/${base}.json "$f";
            rm /tmp/${base}.json;
          done'
        volumes:
          - "{{ pbf_dir }}:/pbf:ro"
          - "{{ routing_dir }}:/out"
        cleanup: true
        detach: false